version: 0.0
os: linux
files:
  - source: /target/s3://nextwork-devops-cicd-joe/6c204dc6-3d86-4acc-8939-6074d13d5964.gz
    destination: /usr/share/tomcat/webapps/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root


